name: 'Terraform Deploy'

on:
  workflow_dispatch:

  push:
    branches-ignore:
      - 'main'
      - 'release/*'

permissions:
  id-token: write
  contents: read
      
jobs:
  dev-plan:
    name: 'Terraform Dev Plan'
    uses: yorkutest/templates/.github/workflows/tf-complete-with-github-runner.yml@main
    with:
      storageAccountInfo: ${{ vars.TF_STORAGE_ACCOUNT_INFO }}
      deploymentType: 'Create'
      commandOptions: '-var-file=terraform.tfvars'
      storageKey: 'dev/firewall/hub_spoke_firewall.tfstate'
      targetEnv: development
    secrets: inherit

